export const LEVELS = [
      "Walker",
      "Stroller",
      "Mover",
      "Pacer",
      "Stepper",
      "Strider",
      "Jogger",
      "Light Jogger",
      "Smooth Jogger",
      "Rhythm Runner",
      "Easy Runner",
      "Trail Trotter",
      "Fresh Foot",
      "Mile Starter",
      "Warm-Up Warrior",
      "Tempo Beginner",
      "Pavement Pupil",
      "Fitness Foot",
      "Cadence Cadet",
      "Stride Seeker",
      "Breath Finder",
      "Treadmill Trotter",
      "Early Sprinter",
      "Mileage Rookie",
      "Track Trainee",
      "First 5K Finisher",
      "Hill Climber",
      "Sprinter Scout",
      "Form Follower",
      "Endurance Explorer",
      "Morning Miler",
      "Weekly Runner",
      "Tempo Tracker",
      "Footpath Flyer",
      "Casual Racer",
      "Speed Scholar",
      "Distance Dreamer",
      "Cadence Chaser",
      "Long Run Learner",
      "Race Ready",
      "Speed Builder",
      "5K Crusher",
      "Urban Runner",
      "Track Technician",
      "Strong Strider",
      "Cruise Controller",
      "Goal Getter",
      "Stamina Seeker",
      "Hill Harrier",
      "Trail Chaser",
      "Distance Devotee",
      "Tenacious Trotter",
      "Progressive Pacer",
      "10K Veteran",
      "Time Tracker",
      "Mid-Pack Mover",
      "Performance Pusher",
      "Long Haul Hero",
      "Half-Marathon Hopeful",
      "Speed Demon",
      "Fuel Finder",
      "Runner of Rhythm",
      "Breath Master",
      "Gear Grinder",
      "Hill Dominator",
      "Marathon Student",
      "Grit Gainer",
      "Mileage Master",
      "Form Finisher",
      "Clock Chaser",
      "Pace Manager",
      "Marathoner",
      "Split Strategist",
      "Endurance Architect",
      "Distance Sculptor",
      "Resilient Runner",
      "Time Shaver",
      "Racing Strategist",
      "Hydration Pro",
      "Effort Expert",
      "Elite Amateur",
      "Advanced Tracker",
      "Pace Commander",
      "Precision Pacer",
      "Personal Best Breaker",
      "Speed Strategist",
      "Recovery King",
      "Distance Dominator",
      "Podium Chaser",
      "Endurance Elite",
      "Race Day Pro",
      "Speed Technician",
      "Half-Marathon Hero",
      "Marathon Machine",
      "Zone Master",
      "Champion Strider",
      "Cadence King",
      "Ultra Hopeful",
      "Effort Engineer",
      "Training Sage",
      "Marathon Master",
      "Peak Performer",
      "Ultra Runner",
      "Pro Runner",
      "Elite Racer",
      "World-Class Runner"
]